export enum PlayActionType {
  DECREMENT_TIMER = 'DECREMENT_TIMER',
  SET_TIMER = 'SET_TIMER',
  INCREMENT_ROUND = 'INCREMENT_ROUND',
}

export enum SettingsActionType {
  DECREMENT_TIME_PER_TURN = 'DECREMENT_TIME_PER_TURN',
  INCREMENT_TIME_PER_TURN = 'INCREMENT_TIME_PER_TURN',
}

export enum GameActionType {
  INCREMENT_PLAYERS_SCORE = 'INCREMENT_PLAYERS_SCORE',
}
