export enum GameActionType {
  DECREMENT_TIMER = 'DECREMENT_TIMER',
  RESET_TIMER = 'RESET_TIMER',
  INCREMENT_ROUND = 'INCREMENT_ROUND',
}

export enum SettingsActionType {
  DECREMENT_TIME_PER_TURN = 'DECREMENT_TIME_PER_TURN',
  INCREMENT_TIME_PER_TURN = 'INCREMENT_TIME_PER_TURN',
}
