---
name: GitHub CI #blah

on:
  push:
    branches-ignore: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Lint Code Base
        run: yarn lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Test Code Base
        run: yarn test:nowatch
