---
name: Notify Team

on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  notify:
    name: Pull Request Notification
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_TEST }}
    steps:
      - name: Send pull request opened to Discord channel
        if: ${{ github.event.action == 'opened' }}
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has a new pull request: {{ EVENT_PAYLOAD.pull_request.html_url }}'
      - name: Send pull request ready for review to Discord channel
        if: ${{ github.event.action == 'ready_for_review' }}
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} pull request is ready for review: {{ EVENT_PAYLOAD.pull_request.html_url }}'
